version: "3.3"
services:
  web-server:
    container_name: web-server
    build:
      context: "./packages/nextjs"
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./packages/nextjs:/home/nextjs'
      - './packages/nextjs/node_modules:/home/node/nextjs/node_modules'
    ports:
      - 8080:3000
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cloudkit
      - MONGO_INITDB_ROOT_PASSWORD=cloudkit
      - MONGO_INITDB_DATABASE=CloudKit
    networks:
      - app-network

volumes:
  mongodb:
  node_modules:


networks:
  app-network:
    driver: bridge